-- Table: call_logs
create table public.call_logs (
  id bigint generated by default as identity not null,
  phone_number text not null,
  donor_name text null,
  call_status text null,
  call_sid text null,
  timestamp timestamp without time zone null default now(),
  constraint call_logs_pkey primary key (id)
) TABLESPACE pg_default;

--Table: donors
create table public.donors (
  "Donor_ID" bigint generated by default as identity not null,
  "Name" text not null default ''::text,
  "Age" smallint not null,
  "Blood_Group" character varying not null,
  "Phone_Number" text not null,
  "DOB" date not null,
  "Location" text not null,
  constraint donors_pkey primary key ("Donor_ID"),
  constraint donors_id_key unique ("Donor_ID")
) TABLESPACE pg_default;

--Table: history
create table public.history (
  id bigint generated by default as identity not null,
  blood_group text not null,
  total_calls integer null,
  answered_calls integer null,
  confirmed_count integer null,
  confirmed_donors jsonb null,
  requested_at timestamp without time zone null default now(),
  constraint history_pkey primary key (id)
) TABLESPACE pg_default;

--Table: confirmed_donors
create table public.confirmed_donors (
  "Donor_ID" bigint generated by default as identity not null,
  "Name" text not null,
  "Age" smallint not null,
  "Blood_Group" character varying not null,
  "Phone_Number" text not null,
  "DOB" date null,
  "Location" text null,
  constraint confirmed_donors_pkey primary key ("Donor_ID"),
  constraint Confirmed Donors_id_key unique ("Donor_ID")
) TABLESPACE pg_default;